#ifndef MODBUSPLUGIN_GLOBAL_H
#define MODBUSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSPLUGIN_LIBRARY)
#  define MODBUSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODBUSPLUGIN_GLOBAL_H
