#ifndef DAI_MODBUSPLUGIN_GLOBAL_H
#define DAI_MODBUSPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSPLUGIN_LIBRARY)
#  define MODBUSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DAI_MODBUSPLUGIN_GLOBAL_H
