#ifndef ONEWIRETHERMPLUGIN_GLOBAL_H
#define ONEWIRETHERMPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ONEWIRETHERMPLUGIN_LIBRARY)
#  define ONEWIRETHERMPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ONEWIRETHERMPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ONEWIRETHERMPLUGIN_GLOBAL_H
