#ifndef WIRINGPIPLUGIN_GLOBAL_H
#define WIRINGPIPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIRINGPIPLUGIN_LIBRARY)
#  define WIRINGPIPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIRINGPIPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIRINGPIPLUGIN_GLOBAL_H
